services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  db:
    image: docker.io/postgis/postgis:16-master
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: munch.settings.development
      DB_HOST: db
    ports:
      - "5431:5432"

volumes:
  postgres_data:
