name: "munch"
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.14
  - pip
  - gdal
  - libvips
  - libjxl=0.11
  - geos
  - proj
  - ipykernel
  - poppler
  - tqdm
  - pip:
    - -r requirements.txt 